package top.duanhong.steward.mapper.gmapper;

import org.apache.ibatis.annotations.Param;
import top.duanhong.steward.entity.po.NetTag;
import top.duanhong.steward.entity.po.NetTagExample;

import java.util.List;

public interface NetTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    long countByExample(NetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int deleteByExample(NetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int insert(NetTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int insertSelective(NetTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    List<NetTag> selectByExampleWithBLOBs(NetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    List<NetTag> selectByExample(NetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    NetTag selectByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NetTag record, @Param("example") NetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") NetTag record, @Param("example") NetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NetTag record, @Param("example") NetTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NetTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(NetTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stew_net_tags
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NetTag record);
}
