package top.duanhong.steward.entity.po;

import java.util.Date;

public class NetTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.tag_id
     *
     * @mbg.generated
     */
    private String tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.tag_title
     *
     * @mbg.generated
     */
    private String tagTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.tag_remark
     *
     * @mbg.generated
     */
    private String tagRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.theme
     *
     * @mbg.generated
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stew_net_tags.tag_path
     *
     * @mbg.generated
     */
    private String tagPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.tag_id
     *
     * @return the value of stew_net_tags.tag_id
     *
     * @mbg.generated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.tag_id
     *
     * @param tagId the value for stew_net_tags.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.create_time
     *
     * @return the value of stew_net_tags.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.create_time
     *
     * @param createTime the value for stew_net_tags.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.tag_title
     *
     * @return the value of stew_net_tags.tag_title
     *
     * @mbg.generated
     */
    public String getTagTitle() {
        return tagTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.tag_title
     *
     * @param tagTitle the value for stew_net_tags.tag_title
     *
     * @mbg.generated
     */
    public void setTagTitle(String tagTitle) {
        this.tagTitle = tagTitle == null ? null : tagTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.tag_remark
     *
     * @return the value of stew_net_tags.tag_remark
     *
     * @mbg.generated
     */
    public String getTagRemark() {
        return tagRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.tag_remark
     *
     * @param tagRemark the value for stew_net_tags.tag_remark
     *
     * @mbg.generated
     */
    public void setTagRemark(String tagRemark) {
        this.tagRemark = tagRemark == null ? null : tagRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.theme
     *
     * @return the value of stew_net_tags.theme
     *
     * @mbg.generated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.theme
     *
     * @param theme the value for stew_net_tags.theme
     *
     * @mbg.generated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.type
     *
     * @return the value of stew_net_tags.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.type
     *
     * @param type the value for stew_net_tags.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.update_time
     *
     * @return the value of stew_net_tags.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.update_time
     *
     * @param updateTime the value for stew_net_tags.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.state
     *
     * @return the value of stew_net_tags.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.state
     *
     * @param state the value for stew_net_tags.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stew_net_tags.tag_path
     *
     * @return the value of stew_net_tags.tag_path
     *
     * @mbg.generated
     */
    public String getTagPath() {
        return tagPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stew_net_tags.tag_path
     *
     * @param tagPath the value for stew_net_tags.tag_path
     *
     * @mbg.generated
     */
    public void setTagPath(String tagPath) {
        this.tagPath = tagPath == null ? null : tagPath.trim();
    }
}